### ISSUE TITLE
Add an easy way to transfer arguments from the activity to a step of the wizard

### ISSUE THREAD

**Issue by pommedeterresautee** [Nimrodda/WizarDroid#17]
Hi,

I wanted to transfer some arguments from the activity to the wizard fragment. Right now I am using OTTO bus which is a bit big for something simple to implement I think.

A simple method can be added to the API:

``` java
public Builder addStep(java.lang.Class<? extends org.codepond.android.wizardroid.WizardStep> stepClass, Bundle b)
```

That way the Bundle would be loaded in the fragment easily!

To get back the Bundle inside the fragment you can let the user do it in the normal way (getArguments()) or may be add some annotation magic stuff. As my knowledge in annotation is very poor, I don't know if it's difficult and may be it s overkilling.

Regards

**Comment by talazoft** [comment]
Sorry, but I don't find any method addStep(Class<? extends WizardStep> stepClass, Bundle arguments) in version 1.3.1, am I using the wrong version?

my gradle file
dependencies {
.....
compile 'org.codepond:wizardroid:1.3.1'
.....
}

**Comment by Nimrodda** [comment]
sounds like you are trying something that was removed in later releases. Please check out the wiki for more info.
