### ISSUE TITLE
Swipe Back/Prev is very sensitive

### ISSUE THREAD

**Issue by JeffInMadison** [Nimrodda/WizarDroid#34]
I have an EditText on one of my WizardStep pages and when I go to select it to enter text 8 times out of ten it will go to the next/previous wizard step because if the touch moves at all it's interpreted as a swipe.

I've also noticed that I can put my finger on the right most side of my screen and if I swipe left I can go multiple pages in one long swipe left. 

I tracked it down to the setOnPageChangeListener in Wizard.java. I cloned the repo and commented out that listener out of curiosity and everything still seems to work. 

Did you override the built in ViewPager funtionality for a reason I am not seeing?

**Comment by virtualvoid** [comment]
I have this issue too, I think this should be configurable. For example :

wizard.setSwipeable(boolean).

**Comment by Nimrodda** [comment]
@virtualvoid you should get the latest version. The issue is fixed.
