### ISSUE TITLE
notifyCompleted(false) throws an Exception

### ISSUE THREAD

**Issue by krlicmuhamed** [Nimrodda/WizarDroid#44]
In my step I use a simple if statement in a onTextChanged event where i check whether the Next button should be disabled or enabled.. I check if the editText is empty if so I use notifyCompleted(false) else notifyCompleted(true).. But looks like when I use notifyCompleted(false) It throws an exception which is called when you might be trying to nest a fragment within other fragment.

Here's my [code](https://gist.github.com/l0oky/e1514e4c8ba3d2a965fe)

Thank you.

**Comment by mehdi1602** [comment]
i have same problem. and as i rechecked my code all thing is right. has this problem been solved yet?
