### ISSUE TITLE
notifyCompleted() throws an Exception

### ISSUE THREAD

**Issue by mehdi1602** [Nimrodda/WizarDroid#50]
i have found if two time in a raw call  notifyCompleted(false) or notifyCompleted(true) it thows an exception of nested fragments. for you form example when i check the middle step and proceed and come back again the exception is thrown. would you please guide me in fixing this.

**Comment by Nimrodda** [comment]
Please make sure you are using the latest WizarDroid version 1.3.0, which has many bug fixes related to your issue. Let me know if that fixed it.

**Comment by mehdi1602** [comment]
unfortunately it is not possible to me to use the library right now. but i'll try later and i 'll inform you about the result.
for now i used a singleton flag + a background thread to handle activating and deactivating of next button. it works good but i feel i am cheating :) please let me know if you think this way has some disadvantage expect for performance (which i handled it somehow using sleeping of background thread)

**Comment by Nimrodda** [comment]
sorry can't help u with workaround. you need to try with latest release and even then, if the issues remains, post your code here. closing this issue, i'll open it if it's a real issue.
