### ISSUE TITLE
Go To Step 

### ISSUE THREAD

**Issue by OwnHno** [Nimrodda/WizarDroid#55]
Hi !
I've actually implemented a result Step, where the user see everything he set in the Wizar.
I just want to know if it's possible (and I tried but don't find how to) to use super.wizard.setCurrentStep() in a Step, then the user can click on a value he wants to change, and the wizard can go on the step.
Thanks for the Wizard, it's a really nice work, and I hope you can clarify this point !

**Comment by Nimrodda** [comment]
Hi, no this feature is not available right now
