### ISSUE TITLE
Multiple variables are not working.

### ISSUE THREAD

**Issue by gcormier** [Nimrodda/WizarDroid#58]
I've got a basic 3 step wizard, and I can only get 1 variable working.

    @ContextVariable
    private String apiPassword;
    @ContextVariable
    private String apiEmail;
    @ContextVariable
    private String fun;

I can't get anything other then apiEmail set. I threw in "fun" to just hardcode set's all over my code, and it's always null on the next page of the wizard. All three steps have that code at the top.

**Comment by gcormier** [comment]
Getting some additional weird behaviour. Code in my onCreateView() in Step #3 is called after pressing "Next" in Step 1. So,

return new WizardFlow.Builder()
                .addStep(EmailStep.class)
                .addStep(PasswordStep.class)
                .addStep(VerifyLoginStep.class, true)
                .create();


VerifyLoginStep.onCreateView() has some log methods, and they get triggered when I complete step 1.

Right now all I'm doing is trying to set 2 variables. Some very odd behavior....

**Comment by Nimrodda** [comment]
This might be related to issue #59 
Please try again with the latest release 1.3.1 and report back if the issue remains.
