### ISSUE TITLE
Passing data from wizard steps to another activity extends ActionBarActivity

### ISSUE THREAD

**Issue by hasnahmd** [Nimrodda/WizarDroid#65]
**\* I am NOT defining an ISSUE here but I am looking for the solution ***

I know that {@ContextVariable} works to pass data between different steps but what if I want to pull out this data and add to my activity. Can anyone guide me or show me an example?

**Comment by Nimrodda** [comment]
Steps in WizarDroid inherit from Fragment. Therefore passing data from Fragment to Activity is the as with standard Fragment http://developer.android.com/training/basics/fragments/communicating.html
Use the step's onExit() to get the user input data from the fields annotated with `@ContextVariable`.
I hope this helps you!
