### ISSUE TITLE
WizardStep's onResume() method not working properly

### ISSUE THREAD

**Issue by Ajmera-Infotech** [Nimrodda/WizarDroid#66]
When you host a view pager in a fragment you have to specify getChildFragmentManager() to its adapter. You have specified activity.getSupportFragmentManager().

You can read this for help : http://stackoverflow.com/questions/14740445/what-is-difference-between-getsupportfragmentmanager-and-getchildfragmentmanag

**Comment by Nimrodda** [comment]
What is the actual bug you're experiencing? Please provide specific details.

**Comment by Ajmera-Infotech** [comment]
I was trying to change labels of the wizard page in on resume method of the wizard steps. But onResume method did not call properly.

**Comment by Nimrodda** [comment]
So is the issue now fixed?

**Comment by Ajmera-Infotech** [comment]
No. It is not.

**Comment by Nimrodda** [comment]
Can you paste your code here?

**Comment by Nimrodda** [comment]
The issue is fixed in the upcoming release.
