### ISSUE TITLE
Problem creating Custom Layout

### ISSUE THREAD

**Issue by oillada** [Nimrodda/WizarDroid#69]
Hello I'm trying to make a custom layout, I follow this tutorial https://github.com/Nimrodda/WizarDroid/wiki/Creating-Custom-Wizard-Layout
but I have an error on the OnCreatView Method Error:(27, 19) error: "method setOnClickListener in class View cannot be applied to given types;
required: OnClickListener
found: QuestionnaireFragment
reason: actual argument QuestionnaireFragment cannot be converted to OnClickListener by method invocation conversion"

I fixed adding:  implements View.OnClickListener to the class
Its ok?

**Comment by Nimrodda** [comment]
Can you paste your code here?

**Comment by Nimrodda** [comment]
Closing as reporter didn't elaborate on the issue
