### ISSUE TITLE
Slow with Images

### ISSUE THREAD

**Issue by rex3du** [Nimrodda/WizarDroid#73]
I use ImageView for each Wizard Step. However, it is extremely slow when going to the next page. 

Is there any solutions? Thank you in advance.

**Comment by Nimrodda** [comment]
I don't see how WizarDroid is related to this issue. WizarDroid is basically a ViewPager wrapper...
What I'd suggest you is to try out a ViewPager directly and see how it goes.
I bet the bitmaps you're having in those ImageViews are huge.

**Comment by rex3du** [comment]
@Nimrodda  Thank you for your help. I fix this by putting image file into drawable-xhdpi directory instead of drawable directory
