### ISSUE TITLE
Custom Layout Problem

### ISSUE THREAD

**Issue by alessandrosilva** [Nimrodda/WizarDroid#76]
I tried implement a custom layout on step wizard. My class  inherit from WizardFragment but I am always told that there is no implementation for the method setActivity(this).

Sory for the bad english!

**Comment by Nimrodda** [comment]
Can you paste your code? Kindda hard to understand what's going wrong...

**Comment by Nimrodda** [comment]
Closing as the OP didn't provide more info as requested.
