### ISSUE TITLE
OnClick (Next and Previous)

### ISSUE THREAD

**Issue by aAboodi** [Nimrodda/WizarDroid#77]
could you please show me how can I override the onClick events of the next button in the fragment of each steps in the wizard. 
In fact, I would like to validate the content of the current step in the next button before proceeding to the next one and/or cancel the click (not to proceed to the next step) if it fails in validation.

**Comment by Nimrodda** [comment]
https://github.com/Nimrodda/WizarDroid/wiki/Controlling-wizard-flow-dynamically
