### ISSUE TITLE
Validate a form before click next

### ISSUE THREAD

**Issue by cheko506** [Nimrodda/WizarDroid#79]
Hi guys I'm wondering if is there a way to validate a form in a fragment before click next button. I've tried a lot of stuffs but I couldn't make it. Thanks in advance.

**Comment by Nimrodda** [comment]
The Wiki has exactly what you're looking for. https://github.com/Nimrodda/WizarDroid/wiki/Controlling-wizard-flow-dynamically
Also the sample that comes along with the library has what you're looking for.
