### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by maayanz** [Nimrodda/WizarDroid#82]
Hi, 
Is there a way to control the viewpager in a way that it will start from the last fragment so swipes will go from right to left?
 this can be done on the regular vp layout however i didnt found a way to control it when using this library

Thanks,

**Comment by Nimrodda** [comment]
Sorry for such a late reply.
It should be possible, but you'd have to use `develop` branch for that as this feature isn't available in the latest release. Checkout `develop` branch, specifically look into class `Wizard` method `public void setViewPager()`. Let me know how it goes.
