### ISSUE TITLE
Leave only 'Next' button on the first step

### ISSUE THREAD

**Issue by vbncmx** [Nimrodda/WizarDroid#88]
Hello, is it possible to leave only 'Next' button on the first step. I mean make it 100% width of the screen, hide 'Previos' and separator.

**Comment by Nimrodda** [comment]
Yes there is, but not with the default wizard layout. You have to make your own. Please check out the wiki pages on how to do that. If you have more questions, feel free to ask.

**Comment by vbncmx** [comment]
Thank you!
