### ISSUE TITLE
How to override Next button functionality

### ISSUE THREAD

**Issue by Zapnologica** [Nimrodda/WizarDroid#90]
I want to override the next button functionality in each step.

basically I want to be able to validate my page before allowing the next to actually happen.

I see two options:

```
@override NextButtonOnClick()
{
 If ValidateForm(){
 super.NextButtonOnClick()
 }
}
```

alternatively maybe there is a function which I can override which determines if the step can go to the next step.

```
@Ovverrdie
public boolean canGoToNextStep()
{
return ValdiateForm()
}
```

**Comment by Nimrodda** [comment]
Please see https://github.com/Nimrodda/WizarDroid/wiki/Controlling-wizard-flow-dynamically for more info on how to do exactly that.
