### ISSUE TITLE
Custom Wizard Layout 

### ISSUE THREAD

**Issue by vbncmx** [Nimrodda/WizarDroid#91]
I'm using wizardroid in my project and I like it very much however when I create custom layout following wiki article (https://github.com/Nimrodda/WizarDroid/wiki/Creating-Custom-Wizard-Layout) I get errors in onSetup method:

//You must override this method and create a wizard flow by
    //using WizardFlow.Builder as shown in this example
    @Override
    public WizardFlow onSetup() {
        return new WizardFlow.Builder()
               **.setActivity(this)  *\*                    //First, set the hosting activity for the wizard
               *\* .setContainerId(R.id.step_container)**    //then set the layout container for the steps.
                .addStep(TutorialStep1.class)           //Add your steps in the order you want them
                .addStep(TutorialStep2.class)           //to appear and eventually call create()
                .create();                              //to create the wizard flow.
    }

The problem is in methods setActivity(...) & setContainerId(...). Android studio says there are no such methods. I tried simply commenting them out - this results showing empty layout (the one I need, but without steps in it). Am I doing something wrong or the wiki article need to be updated?

**Comment by Nimrodda** [comment]
You are right. The Wiki was out-of-date. These methods have been removed but the Wiki wasn't updated.
Thanks!
