### ISSUE TITLE
How do i get image url from all pages in the last page?

### ISSUE THREAD

**Issue by ayubaisa** [Nimrodda/WizarDroid#92]
Hi, how do i get all uri of images I captured from camera in a page from another page? i have tried to using the byte array and the bitmap but it didnt work, tried uri too but couldn't make it work. See code below :

`
Picbmp = (Bitmap) data.getExtras().get("data");
ByteArrayOutputStream stream = new ByteArrayOutputStream();

```
            Picbmp.compress(Bitmap.CompressFormat.PNG, 100, stream);
            byte[] PicbyteArray = stream.toByteArray();

            // convert byte array to Bitmap

            Bitmap photoBmp = BitmapFactory.decodeByteArray(PicbyteArray, 0, PicbyteArray.length);
            photoImage.setImageBitmap(photoBmp);
```

`

i want to pass the image uri that i display in the "photoImage" imageview or other previous pages, so i can render them in the next page

**Comment by Nimrodda** [comment]
First, please don't create duplicate issues.
Passing bitmaps between steps is a bad idea cuz it's slow and takes a lot of memory. You're on the right path with passing URIs. Currently, there is no support for arrays at all, nor URIs. What u can do for now is convert the uri to string. In case of multiple URIs u can make a comma separated string. This is kind of a hack but at least with current version that the only solution I can suggest.
