### ISSUE TITLE
action bar is not showed corrctly

### ISSUE THREAD

**Issue by mahermeg17** [Nimrodda/WizarDroid#98]
hi,
how can I fix this

![device-2016-11-11-183431](https://cloud.githubusercontent.com/assets/4602688/20224336/49ae73e8-a83e-11e6-9650-aeabd48542a0.png)

**Comment by mahermeg17** [comment]
if I scroll down, the action bar is correctly shown and the back/next layout are no more visible, they move down.
So how to pin the action bar and back/previews/next layout and keep just the content layout scrolling if needed.

**Comment by Nimrodda** [comment]
this looks like a stackoverflow kindda question. please ask there.
