### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by alwinkpc** [Nimrodda/WizarDroid#99]
Hi, tried to update myself forking but guess I need to be collaborator.

At https://github.com/Nimrodda/WizarDroid/wiki/Creating-Custom-Wizard-Layout you need to include interface `View.OnClickListener` if you want to include the annotation @Override

Just a small change but anyone adapting their code (like I'm doing now) can understand better the onClick() hack

**Comment by Nimrodda** [comment]
Thanks! 👍
